# Generated by Django 3.0.8 on 2020-07-07 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home Appliences'), ('nocategory', 'No Category Selected')], default='nocategory', max_length=15),
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mybid', models.IntegerField()),
                ('bid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allbids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
