# Generated by Django 3.0.8 on 2020-07-07 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200707_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycomment', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allcomments', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commentedlisting', to='auctions.AuctionListing')),
            ],
        ),
    ]
