# Generated by Django 3.0.8 on 2020-07-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='disc',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mycomment',
            field=models.TextField(null=True),
        ),
    ]
