# Generated by Django 3.0.8 on 2020-07-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200708_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='disc',
        ),
    ]
