# Generated by Django 3.0.8 on 2020-07-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200708_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageurl',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home Appliences'), ('stationary', 'Stationary Objects'), ('computer', 'Computer and Pheripherals'), ('nocategory', 'No Category Selected')], default='nocategory', max_length=15),
        ),
    ]
