# Generated by Django 3.0.8 on 2020-07-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200708_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageurl',
        ),
    ]
